config/routes.rb
Mirasol::Application.routes.draw do
  
  scope "(:locale)", :locale => /en|es/ do
    resources :reservars, path: "reservation", only: [:new, :create]
    resources :eventos, path: "eventos", only: [:new, :create]
    get 'reservation/:cin/:cout' => 'reservars#new_date', as: :reservation_reservar
    get "staticpage/index", path: "home"
    get "staticpage/hotel", path: "hotel"
    get "staticpage/habitaciones", path: "habitaciones"
    get "/habitaciones/:id" => 'staticpage#ver_habitaciones', :as => :habitaciones_info 
    get "staticpage/salones", path: "salones"
    get "staticpage/restoran", path: "restoran"
    get "staticpage/eventos", path: "eventos"
    post "staticpage/reservas", path: "reservas"
    get "staticpage/contacto", path: "contacto"
    post "staticpage/enviar_contacto", path: "enviarContacto"
  end

  root 'staticpage#index'

end

app/models/evento.rb
class Evento < ActiveRecord::Base
	validates_presence_of :nombre, :cedula, :email, :telefono, :salon, :fecha_inicio, :fecha_fin, :tipo_montaje
	#validacion de cedula
	validates :cedula, :length => { :minimum => 7, :maximum => 8 }
	validates_numericality_of :cedula, :only_integer => true

	#validaciones para telefono
  	validates :telefono, :length => { :minimum => 11, :maximum => 13 }
  	validates_numericality_of :telefono, :only_integer => true

	#validacion de email
	validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }

	#validacion de cantidad de personas
	validates :cantidad_personas, :numericality => { :less_than_or_equal_to => 100 }

	#custom validate
	validate :fecha_de_salida_mayor_a_fecha_de_entrada?

	def opcion_seleccionada(seleccion)
		if seleccion == true
			return "Si"
		else
			return "No"
		end
	end

	def fecha_de_salida_mayor_a_fecha_de_entrada?
		cin = Date.strptime(self.fecha_inicio, "%d/%m/%Y")
		cout = Date.strptime(self.fecha_fin, "%d/%m/%Y")
		if cout < cin
			errors.add(:fecha_fin, "No puede ser menor a la fecha de entrada")
		end
	end

end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new(fecha_inicio: DateTime.now.strftime("%d/%m/%Y"), fecha_fin: DateTime.now.strftime("%d/%m/%Y"))
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    params[:evento].parse_time_select!(:hora_inicio)
    params[:evento].parse_time_select!(:hora_culminacion)
    if !evento_params[:hora_inicio].to_s.empty? && !evento_params[:hora_culminacion].to_s.empty?
      params[:evento][:hora_inicio] = params[:evento][:hora_inicio].strftime("%I:%M %p")
      params[:evento][:hora_culminacion] = params[:evento][:hora_culminacion].strftime("%I:%M %p")
    end
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.valid?
        EventoMailer.eventos_email(@evento).deliver
        format.html { redirect_to staticpage_index_path, notice: @evento.nombre+', La solicitud de reserva para su evento ya ha sido enviada' }
        format.json { render action: 'show', status: :created, location: @evento }
      else
        format.html { render action: 'new' }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:nombre, :cedula, :empresa, :fecha_solicitud, :email, :telefono, :salon, :tipo_evento, :cantidad_personas, :fecha_inicio, :fecha_fin, :hora_inicio, :hora_culminacion, :tipo_montaje, :descripcion_evento, :pasapalos_frios, :pasapalos_calientes, :menu_plateado, :tipo_buffet, :estaciones_tematicas, :coffeebreak_matutino, :coffeebreak_vespertino, :mesa_quesos, :descorche_cocteles, :descorche_whisky, :descorche_vino, :descorche_vodka, :barra_coctelera, :refrescos, :colores_motivos, :arreglos_florales, :globos, :toldo, :sonido, :dj, :grupo_musical, :podium, :videobeam, :iluminacion, :imflables, :show_magia, :show_baile, :hora_loca, :barman, :animacion_infantil, :mesoneros, :otros_servicios, :observaciones_adicionales)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/edit.html.haml
%h1 Editing evento

= render 'form'

= link_to 'Show', @evento
\|
= link_to 'Back', eventos_path

app/views/eventos/new.html.haml
= render 'form'

app/views/eventos/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @evento.nombre
%p
  %b Cedula:
  = @evento.cedula
%p
  %b Empresa:
  = @evento.empresa
%p
  %b Fecha solicitud:
  = @evento.fecha_solicitud
%p
  %b Email:
  = @evento.email
%p
  %b Telefono:
  = @evento.telefono
%p
  %b Salon:
  = @evento.salon
%p
  %b Tipo evento:
  = @evento.tipo_evento
%p
  %b Cantidad personas:
  = @evento.cantidad_personas
%p
  %b Fecha inicio:
  = @evento.fecha_inicio
%p
  %b Fecha fin:
  = @evento.fecha_fin
%p
  %b Hora inicio:
  = @evento.hora_inicio
%p
  %b Hora culminacion:
  = @evento.hora_culminacion
%p
  %b Tipo montaje:
  = @evento.tipo_montaje
%p
  %b Descripcion evento:
  = @evento.descripcion_evento
%p
  %b Pasapalos frios:
  = @evento.pasapalos_frios
%p
  %b Pasapalos calientes:
  = @evento.pasapalos_calientes
%p
  %b Menu plateado:
  = @evento.menu_plateado
%p
  %b Tipo buffet:
  = @evento.tipo_buffet
%p
  %b Estaciones tematicas:
  = @evento.estaciones_tematicas
%p
  %b Coffeebreak matutino:
  = @evento.coffeebreak_matutino
%p
  %b Coffeebreak vespertino:
  = @evento.coffeebreak_vespertino
%p
  %b Mesa quesos:
  = @evento.mesa_quesos
%p
  %b Descorche cocteles:
  = @evento.descorche_cocteles
%p
  %b Descorche whisky:
  = @evento.descorche_whisky
%p
  %b Descorche vino:
  = @evento.descorche_vino
%p
  %b Descorche vodka:
  = @evento.descorche_vodka
%p
  %b Barra coctelera:
  = @evento.barra_coctelera
%p
  %b Refrescos:
  = @evento.refrescos
%p
  %b Colores motivos:
  = @evento.colores_motivos
%p
  %b Arreglos florales:
  = @evento.arreglos_florales
%p
  %b Globos:
  = @evento.globos
%p
  %b Toldo:
  = @evento.toldo
%p
  %b Sonido:
  = @evento.sonido
%p
  %b Dj:
  = @evento.dj
%p
  %b Grupo musical:
  = @evento.grupo_musical
%p
  %b Podium:
  = @evento.podium
%p
  %b Videobeam:
  = @evento.videobeam
%p
  %b Iluminacion:
  = @evento.iluminacion
%p
  %b Imflables:
  = @evento.imflables
%p
  %b Show magia:
  = @evento.show_magia
%p
  %b Show baile:
  = @evento.show_baile
%p
  %b Hora loca:
  = @evento.hora_loca
%p
  %b Barman:
  = @evento.barman
%p
  %b Animacion infantil:
  = @evento.animacion_infantil
%p
  %b Mesoneros:
  = @evento.mesoneros
%p
  %b Otros servicios:
  = @evento.otros_servicios
%p
  %b Observaciones adicionales:
  = @evento.observaciones_adicionales

= link_to 'Edit', edit_evento_path(@evento)
\|
= link_to 'Back', eventos_path