config/routes.rb
Mirasol::Application.routes.draw do
  
  scope "(:locale)", :locale => /en|es/ do
    resources :reservars, path: "reservation", only: [:new, :create]
    resources :eventos, path: "eventos", only: [:new, :create]
    get 'reservation/:cin/:cout' => 'reservars#new_date', as: :reservation_reservar
    get "staticpage/index", path: "home"
    get "staticpage/hotel", path: "hotel"
    get "staticpage/habitaciones", path: "habitaciones"
    get "/habitaciones/:id" => 'staticpage#ver_habitaciones', :as => :habitaciones_info 
    get "staticpage/salones", path: "salones"
    get "staticpage/restoran", path: "restoran"
    get "staticpage/eventos", path: "eventos"
    post "staticpage/reservas", path: "reservas"
    get "staticpage/contacto", path: "contacto"
    post "staticpage/enviar_contacto", path: "enviarContacto"
  end

  root 'staticpage#index'

end

app/views/layouts/application.html.haml
!!!
%html
	= render template: "layouts/head"
	%body
		.locale
			.btn-group
				= link_to "EN", { :locale => "en" }, class: "#{I18n.locale == :en ? ('btn btn-locale active';) : ('btn btn-locale';)}"
				= link_to "ES",{ :locale => "es" }, class: "#{I18n.locale == :es ? ('btn btn-locale active';) : ('btn btn-locale';)}"
		.page-header
			- unless browser.modern? # Webkit, Firefox 17+, IE 9+ and Opera 12+
				.container
					.alert.alert-danger
						%button{ type:"button", class: "close", "data-dismiss"=>"alert", "aria-hidden"=>"true"}
							%i.fa.fa-times
						%center
							= raw t("module.browser.validation")+" <strong>#{browser.name}</strong>".html_safe
			.container
				.row
					.col-md-12.col-lg-12.col-sm-12.col-xs-12.div-page
						%h4 MIRASOL HOTEL BOUTIQUE PARAGUANÁ
						%hr
				.row
					.col-md-12.col-lg-12.col-sm-12.col-xs-12.div-page
						%center
							#logo-header
					.row
						.col-md-4.col-lg-4.col-sm-4.col-xs-12.div-page
							%i.fa.fa-phone{style:"font-size: 13px; color:#780032;"}
								%small +58-(0269)-246.16.55
						.col-md-4.col-lg-4.col-sm-4.col-xs-12.div-page
							= link_to new_reservar_path do
								%i.fa.fa-envelope{style:"font-size: 13px; color:#780032;"}
									%small reservaciones@mirasolsuites.com
						.col-md-4.col-lg-4.col-sm-4.col-xs-12.div-page
							= link_to staticpage_contacto_path, 'data-no-turbolink' => true do
								%i.fa.fa-envelope{style:"font-size: 13px; color:#780032;"}
									%small info@mirasolsuites.com
					.t-advisor.hidden-xs.hidden-sm
						%ul
							%li
								%a{:href => "http://www.tripadvisor.com.ve/Hotel_Review-g316095-d4838946-Reviews-Mirasol_Hotel_Boutique-Punto_Fijo_Paraguana_Peninsula_Central_Western_Region.html", :target => "_blank"}
									= image_tag "ta15.jpg", alt: "TripAdvisor", width: "150px";
							%li
								%a{:href => "http://www.tripadvisor.com.ve/Hotel_Review-g316095-d4838946-Reviews-Mirasol_Hotel_Boutique-Punto_Fijo_Paraguana_Peninsula_Central_Western_Region.html", :target => "_blank"}
									= image_tag "ta16.jpg", alt: "TripAdvisor", width: "117px";
					.row
						- if flash[:notice]
							.container
								.alert.alert-success
									%button{ type:"button", class: "close", "data-dismiss"=>"alert", "aria-hidden"=>"true"}
										%i.fa.fa-times
									%center
										= "<strong>#{flash[:notice]}</strong> Pronto nos estaremos comunicando contigo.".html_safe

		= render template: "layouts/navbar"
		= yield
	- unless params[:action] == 'hotel' or params[:action] == 'restoran'
		%footer#footer-body
			.container
				.row
					.col-md-4.col-lg-4.col-sm-12.hidden-xs{style:"padding-top:3%;"}
						%center
							.mirasol-footer
							.row
								.col-md-12.col-lg-12.col-sm-12.col-xs-12.div-page
									%center
										%ul.nav-socials
											%li
												= link_to "https://twitter.com/MirasolHotel", target: "_blank" do
													%span.fa-stack.fa-lg{style:"font-size:30px;"}
														%i.fa.fa-circle.fa-stack-2x{style:"color:#780032;"}
														%i.fa.fa-twitter.fa-stack-1x.fa-inverse
											%li
												= link_to "https://www.facebook.com/pages/Hotel-Mirasol-Suites-CA/290332104428638?ref=hl", target: "_blank" do
													%span.fa-stack.fa-lg{style:"font-size:30px;"}
														%i.fa.fa-circle.fa-stack-2x{style:"color:#780032;"}
														%i.fa.fa-facebook.fa-stack-1x.fa-inverse
											%li
												= link_to "https://instagram.com/mirasolhotelboutique", target: "_blank" do
													%span.fa-stack.fa-lg{style:"font-size:30px;"}
														%i.fa.fa-circle.fa-stack-2x{style:"color:#780032;"}
														%i.fa.fa-instagram.fa-stack-1x.fa-inverse
											%li{style: "margin-left: 5px;"}
												= link_to "http://www.tripadvisor.com/Hotel_Review-g316095-d4838946-Reviews-Mirasol_Hotel_Boutique-Punto_Fijo_Paraguana_Peninsula_Central_Western_Region.html", target: "_blank" do
													%span.fa-stack.fa-lg{style:"font-size:30px;"}
														%i.fa.fa-circle.fa-stack-2x{style:"color:#780032;"}
														%i.fa.fa-tripadvisor.fa-stack-1x.fa-inverse
					.col-md-4.col-lg-4.col-sm-12.col-xs-12{align:"justify"}
						%h3
							%b
								=t("footer.conocenos")
						%p
							=t("footer.conocenos-p")
					.col-md-4.col-lg-4.col-sm-12.col-xs-12{align:"justify"}
						%h3
							%b
								=t("footer.ubicanos")
						%p
							=raw  t('footer.ubicanos-p')
					.col-md-3.col-lg-3.col-sm-12.col-xs-12.visible-xs{align:"justify"}
						%h3
							%b
								Redes Sociales
						%p Amplia presencia en la web...
						%center
							%ul.nav-socials
								%li
									= link_to "https://twitter.com/MirasolHotel", target: "_blank" do
										%span.fa-stack.fa-lg{style:"font-size:30px;"}
											%i.fa.fa-circle.fa-stack-2x{style:"color:#780032;"}
											%i.fa.fa-twitter.fa-stack-1x.fa-inverse
								%li
									= link_to "https://www.facebook.com/pages/Hotel-Mirasol-Suites-CA/290332104428638?ref=hl", target: "_blank" do
										%span.fa-stack.fa-lg{style:"font-size:30px;"}
											%i.fa.fa-circle.fa-stack-2x{style:"color:#780032;"}
											%i.fa.fa-facebook.fa-stack-1x.fa-inverse
								%li
									= link_to "https://instagram.com/mirasolhotelboutique", target: "_blank" do
										%span.fa-stack.fa-lg{style:"font-size:30px;"}
											%i.fa.fa-circle.fa-stack-2x{style:"color:#780032;"}
											%i.fa.fa-instagram.fa-stack-1x.fa-inverse
								%li{style: "margin-left: 5px;"}
									= link_to "http://www.tripadvisor.com/Hotel_Review-g316095-d4838946-Reviews-Mirasol_Hotel_Boutique-Punto_Fijo_Paraguana_Peninsula_Central_Western_Region.html", target: "_blank" do
										%span.fa-stack.fa-lg{style:"font-size:30px;"}
											%i.fa.fa-circle.fa-stack-2x{style:"color:#780032;"}
											%i.fa.fa-tripadvisor.fa-stack-1x.fa-inverse
		#footer
			%center
				= t('footer.autor')
				= image_tag 'slicegroup.png', width: "60px", style: "display: inline; margin-left: 5px; margin-bottom: 3px;"
			%br

:javascript


	var t ;
	$(document).on(
			'DOMMouseScroll mousewheel scroll',
			'body',
			function(){
					window.clearTimeout( t );
					t = window.setTimeout( function(){
							$('.date').datepicker('place')
					}, 1 );
			}
	);

	//reservas
	jQuery(function() {
		var nowTemp = new Date();
		var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);

		var checkin = $('#check-in').datepicker({
				format: "dd/mm/yyyy",
				beforeShowDay: function (date) {
					return date.valueOf() >= now.valueOf();
				},
				autoclose: true

		}).on('changeDate', function (ev) {
			$('#check-out')[0].focus();
		});

		var checkout = $('#check-out').datepicker({
			format: "dd/mm/yyyy",
			beforeShowDay: function (date) {
				return date.valueOf() >= now.valueOf();
			},
				autoclose: true,
			}).on('changeDate', function (ev) {

		});
	});

	//eventos
	jQuery(function() {
		var nowTemp = new Date();
		var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);

		var inciio = $('#evento_fecha_inicio').datepicker({
				format: "dd/mm/yyyy",
				beforeShowDay: function (date) {
					return date.valueOf() >= now.valueOf();
				},
				autoclose: true

		}).on('changeDate', function (ev) {
			$('#evento_fecha_fin')[0].focus();
		});

		var fin = $('#evento_fecha_fin').datepicker({
			format: "dd/mm/yyyy",
			beforeShowDay: function (date) {
				return date.valueOf() >= now.valueOf();
			},
				autoclose: true,
			}).on('changeDate', function (ev) {

		});
	});

app/views/layouts/head.html.haml
%head
	%title Mirasol - Hotel Boutique
	%meta{:content => "MIRASOL HOTEL BOUTIQUE nace como establecimiento focalizado en el área de hospitalidad, ofreciendo sus servicios pensando en el Ejecutivo de hoy, brindando amenidades que superan sus expectativas.", :name => "descrption"}
	= favicon_link_tag 'favicon.png' 
	%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
	%link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:300", :rel => "stylesheet", :type => "text/css"}
	%link{ href:'http://fonts.googleapis.com/css?family=Raleway:400,900', rel:'stylesheet', type:'text/css' }
	%script{src:"https://maps.googleapis.com/maps/api/js?sensor=false"}
	:javascript
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-39728078-1']);
		_gaq.push(['_setDomainName', 'mirasolsuites.com']);
		_gaq.push(['_setAllowLinker', true]);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

	= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
	= javascript_include_tag "application", "data-turbolinks-track" => true
	= javascript_include_tag "home", "data-turbolinks-track" => true
	= csrf_meta_tags

app/views/layouts/navbar.html.haml
%nav.navbar.navbar-default{role: "navigation"}
	.navbar-header
		%button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
			%span.sr-only Toggle navigation
			%span.icon-bar
			%span.icon-bar
			%span.icon-bar
		%div.visible-xs.navbar-brand= "#{t('navbar.items.menu')}"
	#bs-example-navbar-collapse-1.collapse.navbar-collapse
		%ul.nav.navbar-nav
			%li{ class: "#{'active' if params[:action] == 'index'}"}
				= link_to "#{t('navbar.items.home')}", staticpage_index_path 
			%li{class: "#{'active' if params[:action] == 'hotel'}"}
				= link_to "#{t('navbar.items.hotel')}", staticpage_hotel_path 
			%li{ class: "#{'active' if params[:action] == 'habitaciones'}"}
				= link_to "#{t('navbar.items.habitaciones')}", staticpage_habitaciones_path 
			%li{ class: "#{'active' if params[:action] == 'salones'}"}
				= link_to "#{t('navbar.items.salones')}", staticpage_salones_path
			%li{ class: "#{'active' if params[:action] == 'restoran'}"}
				= link_to "#{t('navbar.items.restoran')}", staticpage_restoran_path 
			%li{ class: "#{'active' if params[:action] == 'new'}"}
				= link_to "#{t('navbar.items.eventos')}", staticpage_eventos_path  
			%li{ class: "#{'active' if params[:action] == 'contacto'}"}
				= link_to "#{t('navbar.items.contacto')}", staticpage_contacto_path, 'data-no-turbolink' => true